services:
  api:
    build:
      context: ./api
      target: dev
    environment:
      RAILS_ENV: development

  front:
    build:
      context: ./front
      target: dev
    volumes:
      - ./front:/front
      - /front/node_modules

  sidekiq:
    build:
      context: ./api
      target: dev
