version: "0.1"

services:

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - infra-postgres:/var/lib/postgresql/data
    env_file:
      - .env${ENV_FILE}

  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    volumes:
      - infra-redis:/var/lib/redis/data      

  api:
    build: ./api
    command: bash -c "rm -f /api/tmp/pids/server.pid && foreman start -f /api/Procfile"
    environment:
      - PORT=4000
    volumes:
      - ./api:/api
      - rails_log:/api/log
    links:
      - postgres
      - redis      
    ports:
      - "4000:4000" # use port that you want to in your local instead of 3091
    env_file:
      - .env${ENV_FILE}

  sidekiq:
    build:
      context: ./api
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env${ENV_FILE}

  front:
    build:
      context: ./front
      target: ${TARGET}
    ports:
      - "3000:3000" # use port that you want to in your local instead of 8091
    volumes:
      - ./front:/front
      - front_node_modules:/front/node_modules
    links:
      - api

volumes:
  rails_log:
  front_node_modules:
  app_dotnuxt:
  infra-postgres:
  infra-redis: