services:
  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - infra-postgres:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - infra-redis:/data

  api:
    build:
      context: ./api
      target: prod
    container_name: api
    command: bash -c "rm -f /api/tmp/pids/server.pid && foreman start -f /api/Procfile"
    environment:
      PORT: 4000
      RAILS_ENV: production
    volumes:
      - ./api:/api
      - ./api/log:/api/log
    links:
      - postgres
      - redis
    ports:
      - "4000:4000" # use port that you want to in your local instead of 3091
    env_file:
      - .env

  sidekiq:
    build:
      context: ./api
      target: prod
    container_name: sidekiq
    command: bundle exec sidekiq
    links:
      - postgres
      - redis
    env_file:
      - .env

  front:
    build:
      context: ./front
      target: prod
    container_name: front
    ports:
      - "3000:3000" # use port that you want to in your local instead of 8091
    links:
      - api
    environment:
      NUXT_PUBLIC_CAS_URL: ${CAS_URL}
      NUXT_PUBLIC_BASE_URL: ${BASE_URL}
  web-server:
    image: nginx:1.26-alpine3.20-slim
    container_name: web-server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/blowstack
    ports:
      - 80:80
    depends_on:
      - front
      - api
    restart: unless-stopped

volumes:
  web-root:
  infra-postgres:
  infra-redis:
