fragment ChassisClassFragment on ChassisClassType {
  id
  name
  chassisPowertypeId
  chassisPowertype {
    name
  }
  fournisseur
  model
  partNumber
  vendorEquipmentType
  version
  height
  urlLink
  # frontImage
  # backImage
  customAttributes
  customAttributesDefinition
  allCustomAttributesDefinition
  componentSlots {
    id
    name
    componentTypeId
    description
  }
  portSlots {
    id
    name
    portTypeId
    description
  }
}
