query chassisClassesFile(
  $structOnly: Boolean!
  $chassisPowertypeId: ID
) {
  chassisClassesFile(
    structOnly: $structOnly
    chassisPowertypeId: $chassisPowertypeId
  ) {
    filename
    type
    contentBase64
  }
}