#import '@/graphql/common/tag/tag.fragment.gql'
query chassisFilterTables {
  tags(thingToCount: "chassis") {
    ... TagFragment
  }
  chassisClasses(forFilter: true) {
    id
    name
    ... on ChassisClassFilterTableType {
        numberOfChassis
    }
  }
}