#import './../chassis_class/chassisClass.fragment.gql'

fragment ChassisFragment on ChassisType {
  id
  name
  serialNumber
  chassisClassId
  customAttributes
  chassisClass {
    ...ChassisClassFragment
  }
  ports {
    id
    name
    macAddress
    portTypeId
    description
    connection {
      id
      distantPortId
      linkTypeId
    }
  }
  components {
    id
    name
    componentTypeId
    description
    serialNumber
  }
  tagIds
  tags
}
