#import './chassis.fragment.gql'
query getChassis(
  $nameOrId: String
) {
  getChassis (
    nameOrId: $nameOrId
  ) {
      ...ChassisFragment
  }
  chassisClasses {
    id
    name
  }
  tags {
      id
      name
  }
  availablePorts(
    chassisNameOrId: $nameOrId
  ) {
    id
    name
  }
}
