development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  dna_token:  <%= ENV['DNA_TOKEN'] %>
test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  dna_token:  <%= ENV['DNA_TOKEN'] %>